<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/lbrc-devel/2008-February/index.html" >
   <LINK REL="made" HREF="mailto:lbrc-devel%40lists.berlios.de?Subject=Re%3A%20%5BLbrc-devel%5D%20DBUS%20Daemon%20not%20running%20%28was%3A%20Re%3A%20LBRC%20errors%29&In-Reply-To=%3C1202146588.31943.7.camel%40iphigenie.paessler.home%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000087.html">
   <LINK REL="Next"  HREF="000089.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)</H1>
    <B>Daniel P&#228;&#223;ler</B> 
    <A HREF="mailto:lbrc-devel%40lists.berlios.de?Subject=Re%3A%20%5BLbrc-devel%5D%20DBUS%20Daemon%20not%20running%20%28was%3A%20Re%3A%20LBRC%20errors%29&In-Reply-To=%3C1202146588.31943.7.camel%40iphigenie.paessler.home%3E"
       TITLE="[Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)">paessler at gmx.de
       </A><BR>
    <I>Mon Feb  4 18:36:27 CET 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="000087.html">[Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)
</A></li>
        <LI>Next message: <A HREF="000089.html">[Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#88">[ date ]</a>
              <a href="thread.html#88">[ thread ]</a>
              <a href="subject.html#88">[ subject ]</a>
              <a href="author.html#88">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>
Am Montag, den 04.02.2008, 12:41 +0100 schrieb Daniel Paessler:
&gt;<i> 
</I>&gt;<i> Am Sonntag, den 03.02.2008, 20:09 +0100 schrieb Matthias Bl&#228;sing: 
</I>&gt;<i> &gt; Hey Daniel,
</I>&gt;<i> &gt; 
</I>&gt;<i> &gt; Am Sonntag, den 03.02.2008, 17:46 +0100 schrieb Daniel P&#228;&#223;ler:
</I>&gt;<i> &gt; &gt; 
</I>&gt;<i> &gt; &gt; for me, it looks like this does work, output is:
</I>&gt;<i> &gt; &gt; 
</I>&gt;<i> &gt; &gt; [<A HREF="https://lists.berlios.de/mailman/listinfo/lbrc-devel">paessler at iphigenie</A> pts/4] python
</I>&gt;<i> &gt; &gt; Python 2.5.1 (r251:54863, Jan 10 2008, 19:09:26) 
</I>&gt;<i> &gt; &gt; [GCC 4.2.2 (Gentoo 4.2.2 p1.0)] on linux2
</I>&gt;<i> &gt; &gt; Type &quot;help&quot;, &quot;copyright&quot;, &quot;credits&quot; or &quot;license&quot; for more information.
</I>&gt;<i> &gt; &gt; &gt;&gt;&gt; import bluetooth
</I>&gt;<i> &gt; &gt; &gt;&gt;&gt; socket = bluetooth.BluetoothSocket(bluetooth.RFCOMM)
</I>&gt;<i> &gt; &gt; &gt;&gt;&gt; socket.bind((&quot;&quot;, bluetooth.PORT_ANY))
</I>&gt;<i> &gt; &gt; &gt;&gt;&gt; socket.listen(1)
</I>&gt;<i> &gt; &gt; &gt;&gt;&gt; 
</I>&gt;<i> &gt; &gt; 
</I>&gt;<i> &gt; 
</I>&gt;<i> &gt; Jep, that looks good! But then - you also report, that 0.6 runs as
</I>&gt;<i> &gt; expected. Not sure where the problem lies, but I would suspect a hick-up
</I>&gt;<i> &gt; inside the bluez stack.
</I>&gt;<i> &gt; 
</I>&gt;<i> &gt; 
</I>&gt;<i> &gt; &gt; i recently installed 0.6 and now i get this:
</I>&gt;<i> &gt; &gt; 
</I>&gt;<i> &gt; &gt; 
</I>&gt;<i> &gt; &gt; [<A HREF="https://lists.berlios.de/mailman/listinfo/lbrc-devel">paessler at iphigenie</A> pts/4] LBRCdbus 
</I>&gt;<i> &gt; &gt; LBRC                               : WARNING  Failed to initalize &lt;class
</I>&gt;<i> &gt; &gt; 'LBRC.UinputDispatcher.UinputDispatcher'&gt;
</I>&gt;<i> &gt; &gt; Value -1110949504 out of range for Int32
</I>&gt;<i> &gt; &gt; Traceback (most recent call last):
</I>&gt;<i> &gt; &gt;   File &quot;/usr/bin/LBRCdbus&quot;, line 17, in &lt;module&gt;
</I>&gt;<i> &gt; &gt;     brs = Core()
</I>&gt;<i> &gt; &gt;   File &quot;/usr/lib64/python2.5/site-packages/LBRC/dbusinterface.py&quot;, line
</I>&gt;<i> &gt; &gt; 229, in __init__
</I>&gt;<i> &gt; &gt;     self._register_listener(i)
</I>&gt;<i> &gt; &gt;   File &quot;/usr/lib64/python2.5/site-packages/LBRC/dbusinterface.py&quot;, line
</I>&gt;<i> &gt; &gt; 277, in _register_listener
</I>&gt;<i> &gt; &gt;     self.logger.warn(&quot;Failed to initalize &quot; + str(constructor) + &quot;\n&quot; +
</I>&gt;<i> &gt; &gt; str(e))
</I>&gt;<i> &gt; &gt;   File &quot;/usr/lib64/python2.5/logging/__init__.py&quot;, line 999, in warning
</I>&gt;<i> &gt; &gt;     apply(self._log, (WARNING, msg, args), kwargs)
</I>&gt;<i> &gt; &gt;   File &quot;/usr/lib64/python2.5/logging/__init__.py&quot;, line 1101, in _log
</I>&gt;<i> &gt; &gt;     self.handle(record)
</I>&gt;<i> &gt; &gt;   File &quot;/usr/lib64/python2.5/logging/__init__.py&quot;, line 1111, in handle
</I>&gt;<i> &gt; &gt;     self.callHandlers(record)
</I>&gt;<i> &gt; &gt;   File &quot;/usr/lib64/python2.5/logging/__init__.py&quot;, line 1148, in
</I>&gt;<i> &gt; &gt; callHandlers
</I>&gt;<i> &gt; &gt;     hdlr.handle(record)
</I>&gt;<i> &gt; &gt;   File &quot;/usr/lib64/python2.5/logging/__init__.py&quot;, line 655, in handle
</I>&gt;<i> &gt; &gt;     self.emit(record)
</I>&gt;<i> &gt; &gt;   File &quot;/usr/lib64/python2.5/site-packages/LBRC/dbusinterface.py&quot;, line
</I>&gt;<i> &gt; &gt; 203, in emit
</I>&gt;<i> &gt; &gt;     lr.fmessage)
</I>&gt;<i> &gt; &gt;   File &quot;/usr/lib64/python2.5/site-packages/dbus/decorators.py&quot;, line
</I>&gt;<i> &gt; &gt; 309, in emit_signal
</I>&gt;<i> &gt; &gt;     message.append(signature=signature, *args)
</I>&gt;<i> &gt; &gt; OverflowError: Value -1110949504 out of range for Int32
</I>&gt;<i> &gt; &gt; 
</I>&gt;<i> &gt; &gt; 
</I>&gt;<i> &gt; &gt; could this be an amd64 issue?
</I>&gt;<i> &gt; 
</I>&gt;<i> &gt; Ok, teh OverflowError is not an amd64 error, but it is cause by the
</I>&gt;<i> &gt; signature of the dbus logging method. This is invoked with arguments,
</I>&gt;<i> &gt; that can't fit into the specified int32.
</I>&gt;<i> &gt; 
</I>&gt;<i> &gt; As you can see, the system was not able to initialize the
</I>&gt;<i> &gt; UInputDispatcher (this is the module responsible for injecting
</I>&gt;<i> &gt; keyboard/mouse events into the kernel). Some more information should be
</I>&gt;<i> &gt; provided when run with --debug. But before that the exception has to be
</I>&gt;<i> &gt; tracked down.
</I>&gt;<i> &gt; 
</I>&gt;<i> &gt; As the dbus method call is the problem (its located in line 166 in
</I>&gt;<i> &gt; dbusinterface.py) we should have a look at that. You find the dbus
</I>&gt;<i> &gt; signature in line 166 it should read:
</I>&gt;<i> &gt; 
</I>&gt;<i> &gt; @dbus.service.signal(DBUSIFACE, signature='sisssssidsiisisss')
</I>&gt;<i> &gt; 
</I>&gt;<i> &gt; Replacing every &quot;i&quot; inside the signiture string with an &quot;x&quot; changes the
</I>&gt;<i> &gt; signature to expect an int64, which should do it. But then we won't know
</I>&gt;<i> &gt; which argument is the problem. So if you find the time could you
</I>&gt;<i> &gt; exchange each &quot;i&quot; individually and check whether LBRCdbus works - as in:
</I>&gt;<i> &gt; It does not crash? And then please report the argument that causes the
</I>&gt;<i> &gt; error.
</I>&gt;<i> &gt; 
</I>&gt;<i> &gt; Thanks in advance
</I>&gt;<i> &gt; 
</I>&gt;<i> &gt; Matthias
</I>&gt;<i> &gt; 
</I>&gt;<i> &gt; PS: I really hope we can track this down on the python level. There were
</I>&gt;<i> &gt; problems with amd64 that were caused, because the kernel interface was
</I>&gt;<i> &gt; 64bit, but the userland was 32bit. To circumvent this, a small
</I>&gt;<i> &gt; C-Programm was created, that is compiled with 64bit and connects to the
</I>&gt;<i> &gt; dbus and translates.
</I>&gt;<i> 
</I>&gt;<i> i only can access my machine remote from work at the moment. but
</I>&gt;<i> changing the mentioned line to
</I>&gt;<i> 
</I>&gt;<i> @dbus.service.signal(DBUSIFACE, signature='sisssssidsixsisss')
</I>&gt;<i> 
</I>&gt;<i> seems to work, as it gives no error. of course i can't try bluetooth
</I>&gt;<i> now, but i will do so this evening.
</I>&gt;<i> thanks for your quick answer ;)
</I>&gt;<i> 
</I>&gt;<i> daniel 
</I>

ok, i'm at home now and what should i say? it works ;) thank you again
for your help.
one thing i figured out is, when the connection is lost between the
devices, the j2me application on my se k750i hangs and i have to power
off my phone to get rid of it...
maybe there's a way to kind of &quot;park &quot; the logical connection on lost of
physical connection or something, or at least disconnect properly.

daniel


</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000087.html">[Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)
</A></li>
	<LI>Next message: <A HREF="000089.html">[Lbrc-devel] DBUS Daemon not running (was: Re: LBRC errors)
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#88">[ date ]</a>
              <a href="thread.html#88">[ thread ]</a>
              <a href="subject.html#88">[ subject ]</a>
              <a href="author.html#88">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/lbrc-devel">More information about the Lbrc-devel
mailing list</a><br>
</body></html>
